// Code generated by MockGen. DO NOT EDIT.
// Source: filestore.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	models "github.com/mspraggs/hoard/internal/filestore/models"
	models0 "github.com/mspraggs/hoard/internal/models"
)

// MockBucketSelector is a mock of BucketSelector interface.
type MockBucketSelector struct {
	ctrl     *gomock.Controller
	recorder *MockBucketSelectorMockRecorder
}

// MockBucketSelectorMockRecorder is the mock recorder for MockBucketSelector.
type MockBucketSelectorMockRecorder struct {
	mock *MockBucketSelector
}

// NewMockBucketSelector creates a new mock instance.
func NewMockBucketSelector(ctrl *gomock.Controller) *MockBucketSelector {
	mock := &MockBucketSelector{ctrl: ctrl}
	mock.recorder = &MockBucketSelectorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBucketSelector) EXPECT() *MockBucketSelectorMockRecorder {
	return m.recorder
}

// SelectBucket mocks base method.
func (m *MockBucketSelector) SelectBucket(fileUpload *models0.FileUpload) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SelectBucket", fileUpload)
	ret0, _ := ret[0].(string)
	return ret0
}

// SelectBucket indicates an expected call of SelectBucket.
func (mr *MockBucketSelectorMockRecorder) SelectBucket(fileUpload interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SelectBucket", reflect.TypeOf((*MockBucketSelector)(nil).SelectBucket), fileUpload)
}

// MockEncryptionKeyGenerator is a mock of EncryptionKeyGenerator interface.
type MockEncryptionKeyGenerator struct {
	ctrl     *gomock.Controller
	recorder *MockEncryptionKeyGeneratorMockRecorder
}

// MockEncryptionKeyGeneratorMockRecorder is the mock recorder for MockEncryptionKeyGenerator.
type MockEncryptionKeyGeneratorMockRecorder struct {
	mock *MockEncryptionKeyGenerator
}

// NewMockEncryptionKeyGenerator creates a new mock instance.
func NewMockEncryptionKeyGenerator(ctrl *gomock.Controller) *MockEncryptionKeyGenerator {
	mock := &MockEncryptionKeyGenerator{ctrl: ctrl}
	mock.recorder = &MockEncryptionKeyGeneratorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEncryptionKeyGenerator) EXPECT() *MockEncryptionKeyGeneratorMockRecorder {
	return m.recorder
}

// GenerateKey mocks base method.
func (m *MockEncryptionKeyGenerator) GenerateKey(fileUpload *models0.FileUpload) (models0.EncryptionKey, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateKey", fileUpload)
	ret0, _ := ret[0].(models0.EncryptionKey)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateKey indicates an expected call of GenerateKey.
func (mr *MockEncryptionKeyGeneratorMockRecorder) GenerateKey(fileUpload interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateKey", reflect.TypeOf((*MockEncryptionKeyGenerator)(nil).GenerateKey), fileUpload)
}

// MockUploader is a mock of Uploader interface.
type MockUploader struct {
	ctrl     *gomock.Controller
	recorder *MockUploaderMockRecorder
}

// MockUploaderMockRecorder is the mock recorder for MockUploader.
type MockUploaderMockRecorder struct {
	mock *MockUploader
}

// NewMockUploader creates a new mock instance.
func NewMockUploader(ctrl *gomock.Controller) *MockUploader {
	mock := &MockUploader{ctrl: ctrl}
	mock.recorder = &MockUploaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUploader) EXPECT() *MockUploaderMockRecorder {
	return m.recorder
}

// Upload mocks base method.
func (m *MockUploader) Upload(ctx context.Context, upload *models.FileUpload) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Upload", ctx, upload)
	ret0, _ := ret[0].(error)
	return ret0
}

// Upload indicates an expected call of Upload.
func (mr *MockUploaderMockRecorder) Upload(ctx, upload interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Upload", reflect.TypeOf((*MockUploader)(nil).Upload), ctx, upload)
}
